### ISSUE TITLE
This is "nucypher-kms-umbral" - does that mean that it is purpose-gnostic toward a KMS?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#1]
In other words: Is this a general-purpose proxy reencryption library?  Or a framework for making KMS's?

**Comment by tuxxy** [comment]
I gave it this name to move it from `nucypher-pre-python` for the time being since it is tacking in some frameworking stuff that could be a separate repo eventually.

I couldn't come up with a name for it that I thought was reasonable, so I just followed the seemingly similar naming schema for other things `nucypher-kms-<thing>` and I didn't want to replicate `nucypher-pre-python`. I guess I could have called it `nucypher-pre-umbral`, but I just now thought of it.

It's not specific for the KMS, if you have a better name, I'd love to hear it.

**Comment by cygnusv** [comment]
I think it's closer to a general purpose PRE library, but not because we are looking for that. It's simply a matter of modularity. The cryptographic scheme itself doesn't have to deal with KMS stuff, in principle it could be used for any application, but of course, it has been built always with the KMS in our heads.

If necessary, the name of the repo could change, of course.

**Comment by jMyles** [comment]
How about just "umbral" or "pyUmbral"?

**Comment by tuxxy** [comment]
I like the sound of `pyUmbral`.

**Comment by jMyles** [comment]
Yeah me too - it suggests that implementations in other languages might happen later.

**Comment by tuxxy** [comment]
I'll change it when @cygnusv acknowledges this and also consents.

**Comment by cygnusv** [comment]
Not a big fan of pyumbral, perhaps just umbral, but in the end it's just the name of the repo. In any case, go ahead with the change :)
