### ISSUE TITLE
Tightening up Capsule and ReconstructedCapsule

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#10]
We are using the term "encapsulate" as a sort of loanword from vanilla KEM schemes.  Thus, we also inherit the derived noun "Capsule."

But what is a `Capsule`?  Here's a dictionary definition from MW that is the best for our purposes among their options:

>  noun cap·sule \ ˈkap-səl , -(ˌ)sül also -ˌsyül \  *a compact often sealed and detachable container or compartment*

So, when I was reading the code, following `test_m_of_n`, I expected the following narrative:

* `Bob`, via a side-channel, finds out that there is A Secret that is meant for his eyes.
* `Bob` seeks at least `m` `Ursulas`, getting from each of them a `CapsuleFragment`
* Once Bob finds that he is in possession of a Critical Mass of `CapsuleFragments`, he is able to assemble ("reconstruct") a `Capsule` (in this case, we've been calling it a `ReconstructedCapsule`) and open it, finding The Secret inside.

However, here's what actually happens:

* `Alice` informs `Bob` of A Secret meant for him, and gives `Bob` a bulk ciphertext, which includes a `Thing`.  Heretofore, we've called this thing a `Capsule`.
* Although `Bob` is made to believe that the `Thing` is a capsule, he doesn't open it.  Instead, `Bob` gives the `Thing` to at least `m` `Ursulas`.
* In return, each `Ursula` gives `Bob` a `CapsuleFrag`.
* `Bob` is able to `combine` these `CapsuleFrags` to make a `Capsule` (again, this is a `ReconstructedCapsule`).
* `Bob` opens this (reconstructed-) capsule, and The Secret is inside.

So what is the `Thing`?  

It's not a `Capsule` by the dictionary definition to anyone other than arguably `Alice`, who finds that she can open it and peer inside.

As I read the code, this blocked my ability to reason about it and move forward.  It is clear that the thing that `Alice` gives to `Bob` is not a `Capsule` in any meaningful way, and in fact `Bob` does not use it the way a `Capsule` is used in a KEM scheme if I understand correctly.

Moreover, I have been left with a sense that these two things are actually things of the same shape, and are maybe even the very same thing (recall my proposal that they inherit from the same class).

Then @tuxxy made [this proposal|https://github.com/nucypher/pyUmbral/pull/9#discussion_r159512006] which I think makes sense:

> Would it be beneficial to add Bob's components to the Capsule object and have them be None initialized by default?

> This way when Bob reconstructs it, it's the same capsule object? The addition of these properties would simply be a method on the class or something.

This makes a great deal of sense to me.  Then, the life of the capsule is such that:

* `Alice` creates the `Capsule`.
* Upon creation, `Alice` can open the `Capsule` (ie, `capsule.is_openable_by_alice == True`).
* Then, she gives the `Capsule` to `Bob`, who is unable to open it - it is only openable by Bob once it has all of a Critical Mass of fragments adhered.
* `Bob` gathers the `CapsuleFragments` in the usual way: handing the `Capsule` to Ursula for examination.
* Once `Bob` has adhered a Critical Mass of `CapsuleFragments` to the `Capsule`, it becomes `openable_by_bob`.

I'm not sure this is perfect, but it is the best metaphor I've heard yet.  I think it makes the narrative of the `decapsulte_reencrypted` method far, far clearer.

**Comment by jMyles** [comment]
@cygnusv points out, in another thread:

> Bob doesn't need the original Capsule to open the ReCapsule (i.e., he can compute the derived symmetric key without it), but he needs it to check the validity of the ReCapsule (in the sense of having a guarantee that the ReCapsule is indeed related to the original Capsule).

In such a scenario, I propose that, rather than thinking of it as an "original" capsule, we regard it as `capsule.is_openable_by_alice == False`.

> Something similar happens with the check_challenge method, where Bob also needs the original Capsule to check the correctness.  

Sure, that's fine - and of course that's exactly what happens in `test_m_of_n`.

> One could then say that the correctness check during decryption could be made separately, but cryptographically it's much better to return an error as the result of the decryption in case this check fails, instead of letting the user obtain a "wrong" response (e.g., this could be used to attack Bob).

Oh heck yeah.  I think we all agree there.

**Comment by cygnusv** [comment]
> As I read the code, this blocked my ability to reason about it and move forward. It is clear that the thing that Alice gives to Bob is not a Capsule in any meaningful way, and in fact Bob does not use it the way a Capsule is used in a KEM scheme if I understand correctly.

Both are `Capsules' since both are encapsulating a symmetric key following a KEM approach. I don't think I heard the term Capsule in this sense in crypto papers, but it makes total sense. OK, so although both are Capsules, they do differ on (1) who can open them, and (2) what are they made of. 

Regarding tuxxy's proposal, I have to say that at first I was not very convinced, but I'm starting to like it. To be clear, we use the same class in both cases (i.e., creation by Alice and decryption by Bob), but in Bob's case it is necessary to attach the Critical Mass of CFrags to the capsule, so he can combine them, right? What I like of this, is that some methods (e.g., the former `combine`, now `reconstruct_capsule') could be a Capsule method, rather than a PRE method. This makes sense since c¡the combination doesn't require any secret key.

**Comment by tuxxy** [comment]
Yes, I really like this.

Moving the `reconstruct_capsule` method to `Capsule` makes a lot of sense to me. It allows us to handle the `Umbral` namespace a bit better, imho.

**Comment by jMyles** [comment]
> Both are `Capsules' since both are encapsulating a symmetric key following a KEM approach.

Just to be cagey here: is it?  Unless I'm misunderstanding something (which is possible since I've only been reading KEM material for a few days now), in a KEM Alice necessarily encrypts the sym key for *somebody else* (ie, Bob).  So I think it's disputable whether a thing is a capsule if the contained key can only be read by Alice.  Not that it really matters - it sounds like we have stumbled upon a better metaphor anyway.  :-)

> It allows us to handle the Umbral namespace a bit better, imho.

Agreed, @tuxxy.  That might be the biggest advantage in the end.  Currently, the PRE class really reads more like a module (somewhat mirroring the evolution of `nkms.crypto.api` in the KMS repo).

**Comment by cygnusv** [comment]
KEM is traditionally used in public-key encryption (without re-encryption), so the only possible recipient is always the owner of the public key used during encapsulation. In this case, if our original capsules are created with Alice's public key then they only can be opened by Alice. 

When we add proxy re-encryption to the mix, this doesn't change: original capsules are still only openable by Alice. What PRE adds is the possibility of transforming the original capsules into something else (in our case a ReconstructedCapsule, where cFrags are sort of intermediary data) that can be opened by someone else (e.g., Bob). 

By the way, as far as I know, Umbral is the first KEM-based PRE scheme, so all previous references to KEM in the literature are talking about traditional public-key encryption, where Capsules created with Alice's public key can only be opened by Alice. 

> in a KEM Alice necessarily encrypts the sym key for somebody else (ie, Bob)

I sense that maybe there is a misunderstanding here with the fundamentals of public-key encryption (perhaps not, but I prefer to clarify it). Let us assume that original capsules are always created with Alice's public key (which is our convention). When we say that "Alice creates a capsule", this is giving the idea that Alice is the only one capable of doing that. But this is not true, since this could be done by anyone knowing the public key, because it is (or at least, could be) public. Actually it doesn't matter at all who creates the original capsule, the only thing that matters is who is the owner of that public key, since that person will be the only one that can open the capsule. As I said before, this is true in public-key encryption KEMs and in proxy re-encryption KEMs. The difference is that in PRE it is possible to obtain a new capsule openable by Bob.

**Comment by jMyles** [comment]
Well, sure - in the strictest sense, it's of course true that a key encapsulated for Alice is openable by Alice, whether created by Alice or someone else.

My point was more that the KEM scheme is something of a non-sequitur when it *is* Alice encrypting only for Alice.  It only really becomes a "capsule," or at least a fully-realized capsule, in the sense that it can be opened by the intended recipient of the underlying message, *after* the PRE step.  

I do like the life cycle described above - it's the same capsule, first openable by Alice, then by Bob.  That's pretty easy to understand.  I imagine Bob digging it up out of the dirt, to find that there are "slots" on the side of it.  He must insert fragments in those slots in order for the Capsule to "come alive" and be openable.
