### ISSUE TITLE
Remove ReconstructedCapsule?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#21]
I've been thinking about the removing ReconstructedCapsules because I think they don't have enough justification. You see, only Capsules and cFrags will actually see the Real World (i.e., being serialized, stored and sent over a network). On the contrary, ReconstructedCapsules only make sense as an intermediary state after the moment that Bob takes a bunch of cFrags and combines it, but before he decrypts it. I don't see why Bob would need to save this state. The only exception I see right now is if he wants to decrypt it again in the future (in this case, he only needs to decrypt the ReconstructedCapsule, and doesn't have to bother about cFrags and their combination).

So, my question is: is this last exception enough to justify the existence of ReconstructedCapsule?

Just a thought: if I had put the code of Combination (currently named Reconstruction) inside the decryption when I designed Umbral, then ReconstructedCapsules wouldn't exist right now.

By the way, just to let you know that for the Umbral paper, I already dropped the ReconstructedCapsule concept. Instead, Bob's decryption simply takes the cFrags as input and combines them inside. Anyway, this doesn't affect whatever we decide for the code of Umbral.

**Comment by tuxxy** [comment]
I am not opposed to this.

In my opinion, if they're storing the secret for later use them they aren't
using the KMS securely. The proper way would be to store `m - 1` CFrags and
to then request re-encryption for the last KFrag.

On Jan 17, 2018 04:20, "David Núñez" <notifications@github.com> wrote:

I've been thinking about the removing ReconstructedCapsules because I think
they don't have enough justification. You see, only Capsules and cFrags
will actually see the Real World (i.e., being serialized, stored and sent
over a network). On the contrary, ReconstructedCapsules only make sense as
an intermediary state after the moment that Bob takes a bunch of cFrags and
combines it, but before he decrypts it. I don't see why Bob would need to
save this state. The only exception I see right now is if he wants to
decrypt it again in the future (in this case, he only needs to decrypt the
ReconstructedCapsule, and doesn't have to bother about cFrags and their
combination).

So, my question is: is this last exception enough to justify the existence
of ReconstructedCapsule?

Just a thought: if I had put the code of Combination (currently named
Reconstruction) inside the decryption when I designed Umbral, then
ReconstructedCapsules wouldn't exist right now.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nucypher/pyUmbral/issues/21>, or mute the thread

**Comment by cygnusv** [comment]
> The proper way would be to store `m - 1` CFrags and
> to then request re-encryption for the last KFrag.

Why? (BTW, I guess you meant "CFrag" instead of KFrag right?)

**Comment by tuxxy** [comment]
I meant KFrag, but I should've said "request re-encryption _with_ the last
KFrag."

The reason being that key management is supposed to enable the user to not
have to store keys (even the ciphertext) on their machines or codebases for
that matter.

Storing `m - 1` creates an easy and low latency method of using the KMS in
high demand scenarios, but also in a secure manner without storing the
plaintext or the ciphertext of the secret.


On Jan 17, 2018 08:12, "David Núñez" <notifications@github.com> wrote:

The proper way would be to store m - 1 CFrags and
to then request re-encryption for the last KFrag.

Why? (BTW, I guess you meant "CFrag" instead of KFrag right?)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nucypher/pyUmbral/issues/21#issuecomment-358334704>,
or mute
the thread

**Comment by cygnusv** [comment]
OK, so storing `m-1` is like a secure way of "caching" the re-encryption. I can see your point. 
Just to clarify for future reference, it would only be necessary to ask for re-encryption to any available Ursula that (1) has a KFrag compatible with the rest and (2) hasn't produced any of the cached `m-1` CFrags.

**Comment by tuxxy** [comment]
Yeah, that's right.

Ideally, caching would probably be a part of the KMS API, not Umbral. I
think it would involve just storing a list of some nodes who haven't
performed re-encryption yet. Once a reliable node has been identified, it
can just reuse that same one, but I think it would be neat to cycle through
all the nodes that haven't been used to distribute traffic on the network.

**Comment by cygnusv** [comment]
OK, let's wait for @jMyles and @michwill input...

**Comment by jMyles** [comment]
Yeah, I'm in favor of this.  In fact, I thought that, based on #10, we were already agreed in this, and that, once Bob affixed the proper number of cFrags, the very same `Capsule` simply becomes `openable_by_bob`.

**Comment by tuxxy** [comment]
Sounds like we're in consensus that this should be removed.

Let's talk about what that process is going to look like and how `Capsule` is going to change.

**Comment by jMyles** [comment]
Per Slack, I'm giving it a try.  Basically, I'm going to change the instantiation to a mutation and let Bob keep the same `Capsule` (per our discussion in #10).

**Comment by tuxxy** [comment]
Resolved in #38.
