### ISSUE TITLE
File encryption?

### ISSUE THREAD

**Issue by dominic-healid** [nucypher/pyUmbral#247]
Anyone can give me a sample code for encrypting file? My idea is to upload the encrypted file on IPFS.

**Comment by RiccardoM** [comment]
In order to properly encrypt and later decrypt a file you have to read it's content as bytes. In order to do so, you can use the following code: 

```python3
# Read the file
file = open("path/to/my/file.txt", "rb")   # The "rb" clause tells the open method to read the file as bytes
plaintext = file.read()

# Encrypt it
ciphertext, capsule = pre.encrypt(alices_public_key, plaintext)
```

Then you can proceed with all your operations as usually. 
If you want to store the encrypted file content's inside a new file, you can use the following method: 

```python3
encrypted_file = open("file/to/my/encrypted_file.txt", "wb")  # The wb clause tells the open method to open the file in order to write bytes inside it
encrypted_file.write(ciphertext)
```

Then, you can simply upload inside IPFS the created `encrypted_file.txt` file which will contain the encoded data.

**Comment by cygnusv** [comment]
@dominic-healid I think this answers your question. Thanks @RiccardoM!

**Comment by dominic-healid** [comment]
Thanks guys! @RiccardoM @cygnusv 

My other question right now is how can I send the re-encryption key to the nodes? I believe on the provided sample we just simulate a node.
