### ISSUE TITLE
Obfuscate reencryption that does pass verification.

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#39]
In `PRE.reencrypt`, instead of raising an error, perhaps we want to give a indistinguishable garbage.

**Comment by cygnusv** [comment]
I had that as a TODO note in the reencrypt method, but I have to think about the best way to do it. 
Now that I think of, it may be better, from the crypto point of view, to raise an error, since we would be giving less side-channel information (i.e., timing of scalar multiplication). 

So currently, I lean towards raising an error.

**Comment by jMyles** [comment]
I do agree that raising an error is the more elegant solution and the one that is more likely desired, but this seems like throwing the baby out with the bathwater.

Why not:

* return a tuple either way, with the first element being the result or indistinguishable garbage, and then the second element being a bool of whether it was successful.

Then, the user can decide what to reveal to the network.

We can also optionally accept a kwarg `(..., fuzz=True)`, which, if True, will cause this function to perform some time fuzzing.  

What do you think of that?

**Comment by cygnusv** [comment]
"Then, the user can decide what to reveal to the network"

 If the verification prior the re-encryption fails, then the input provided
by Bob was garbage. What you propose is to respond garbage with garbage.
What's the advantage of perpetuating garbage in the network?

El 27/1/2018 17:48, "Justin Holmes" <notifications@github.com> escribió:

I do agree that raising an error is the more elegant solution and the one
that is more likely desired, but this seems like throwing the baby out with
the bathwater.

Why not:

   - return a tuple either way, with the first element being the result or
   indistinguishable garbage, and then the second element being a bool of
   whether it was successful.

Then, the user can decide what to reveal to the network.

We can also optionally accept a kwarg (..., fuzz=True), which, if True,
will cause this function to perform some time fuzzing.

What do you think of that?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nucypher/pyUmbral/issues/39#issuecomment-360997374>,
or mute
the thread

**Comment by jMyles** [comment]
For the KMS, you're right that this makes no sense.

However, for other applications, I can imagine a use case for obfuscating the result so that a malicious Bob can't know whether the reencryption was successful, in order to disincentivize various guessing attacks.   Or maybe I'm not thinking this through?

**Comment by tuxxy** [comment]
Oh yeah, definitely, but this probably doesn't fit in Umbral itself. It'd
be up to the user to capture the error and return the garbage.

**Comment by jMyles** [comment]
I'm less certain.  Once umbral raises an error, the user will never be able to catch it and return garbage in time to overcome a timing attack (without adding an enormous fuzz to successful reencryptions).  Right?  Or maybe I'm not right?  :-)

**Comment by cygnusv** [comment]
My initial concern for timing attacks here was unjustified. In fact, it's the opposite. Since checking the validity of the initial input can be performed by anyone (including Bob), the fact that Ursula simply responds with an error when Bob's input was garbage doesn't add any information, as Bob could know this from the beginning. 

By the way, the usual way in any crypto primitive when for responding to a gargabe input is an error, not more garbage. Let's don't swim against the current here. We can however add a big time delay, but I agree that umbral is not the place to do this.

**Comment by jMyles** [comment]
OK, sounds good!  I'll fix and close.

**Comment by jMyles** [comment]
So, does it make sense to raise a more informative error?

**Comment by cygnusv** [comment]
Yes, in this case we can say that the input capsule is not valid, or something similar
