### ISSUE TITLE
"capsule_maker_public_key"

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#42]
About using the name `capsule_maker_public_key` to describe the public key used to (I believe) verify the accuracy of the activated components during decapsulation, @cygnusv says:

> Opener_private_key is OK, but capsule_maker_pub_key it's not, since in principle anyone (even if they don't have any keys) can be a capsule maker. Anyway, this is just a comment on naming. Let's simply put it in our TODO list.

However, doesn't this indeed need to be the very key that was used in the original encapsulation?  And isn't someone who encapsulates a capsule maker?

Or have I missed a crucial detail?  :-)

**Comment by cygnusv** [comment]
> However, doesn't this indeed need to be the very key that was used in the original encapsulation? 

Yes

> And isn't someone who encapsulates a capsule maker?

No. Who encapsulates doesn't need to have a public key. He needs to provide a public key of the intended recipient (Alice), but not his public key (in fact, the capsule maker may don't even have a public key!). With proxy re-encryption, we can change the public key of the recipient in the ciphertext, and put a different one, so that the intended recipient changes (e.g. to Bob).

Having said that, currently we assume that is Alice who encrypts for herself (I remember we discussed that a few days ago), but this assumption is not compatible with some of the applications that are envisioned (e.g., encrypted chats). Maybe we should get rid of this assumption.

**Comment by tuxxy** [comment]
Can we resolve this by reverting back to naming schemes like `alice/bob_pubkey` and `alice/bob_privkey`?

**Comment by cygnusv** [comment]
I'm completely in favor of using the Alice and Bob names.

**Comment by jMyles** [comment]
Me too, but in this case we're not sure it will be Alice, right?

**Comment by cygnusv** [comment]
I think you are still confused. It is Alice because the original public key for encapsulation is always Alice's, regardless if it is Alice herself who is creating the capsule or someone else.

**Comment by jMyles** [comment]
> I think you are still confused.

Correct, sir!  :-)

Can you give me a scenario in which Alice does the encapsulation, but somebody else makes the `Capsule`?

**Comment by cygnusv** [comment]
Mmm making the capsule is the encapsulation, so I don't get your question.

**Comment by jMyles** [comment]
Yeah, that's what I thought also.
'
So then, I don't understand this dynamic:

> It is Alice because the original public key for encapsulation is always Alice's, regardless if it is Alice herself who is creating the capsule or someone else.

**Comment by tuxxy** [comment]
Resolved in #46
