### ISSUE TITLE
What are 'e', 's', 'u', and 'v'?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#5]
Throughout `umbral.umbral`, classes have one-letter attributes.  What are these?

(I imagine perhaps `v` is version?)

**Comment by cygnusv** [comment]
This is related with [#2](https://github.com/nucypher/nucypher-kms-umbral/issues/2). I think it's difficult to come with informative names, and individual explanations of what does each element represents, since in several cases, they have some collective functionality. For example, 's' and 'v' are, together, something similar to a signature that is used during the ciphertext validations, but separately they don't have any special meaning, and to make things more difficult, 'v' is also used as key material to the KDF (which is completely unrelated to the signature functionality). 

In any case, I'll try to improve this and provide a minimal documentation.

**Comment by jMyles** [comment]
Perhaps we need to wrap this in some kind of metaphor to make it easier to reason about.  Since there are so many constituent attributes, making a cooking / baking thing?  Can you imagine `e`, `s`, `u`, `v` (and I also see `x`) being ingredients in a cake or something?

**Comment by cygnusv** [comment]
I really don't see it. In the end, they wouldn't be metaphors, just arbitrary names. I think I can come up with names that convey much more what is the role of each element, although possibly they would be very boring, academic names :-P

**Comment by tuxxy** [comment]
@cygnusv I think that would be preferable to single character variables from an engineering perspective here.

**Comment by jMyles** [comment]
Well, boring academic names are much better than single letters.  :-)

Without understanding the mechanics of this thing, it's hard for me to help you craft an appropriate metaphor.

We already have `Capsule` now, which is a potent metaphor.

Is it plausible to somehow fit the `Challenge` concepts around the `Capsule` metaphor?

**Comment by cygnusv** [comment]
Ok, let's continue the Challenge discussion in the other thread, and leave this for the variable names.

**Comment by cygnusv** [comment]
OK, something that would be very interesting is to append/prepend something to the variable names to indicate whether they are EC points or bignums. For example, in Capsule, 'e' and 'v' are EC Points, while 's' is a bignum. 
Of course, 'e', 'v' and 's' would also have a new name, but probably that would help too wrt to clarity.

**Comment by tuxxy** [comment]
That would actually do a lot. At least on the logic side. That clarifies a ton.

**Comment by tuxxy** [comment]
Something along the lines of `point_<var>` and `bn_<var>`?

**Comment by cygnusv** [comment]
Yes, something like that. I actually don't like it because of the verbosity, but I have to admit that it makes things more readable. In an academic paper I would simply use uppercase/lowercase to distinguish, or greek letters, or whatever, but here it's not possible. 

What I'm facing right now is that, for example, several of the elements that are EC points are basically ephemeral public keys, with little difference between them actually. What do you think of adding to the single-letter names,a prefix to clarify what are them? For example:

- 'e' --> point_eph_e
- 'v' --> point_eph_v
- 'x' --> point_eph_x

In case you are wondering, 'e' and 'v' are used basically as input to the KDF, and 'x' is used to make Umbral non-interactive, but I don't see how that can be reflected easily in a name. 

's', 'z1', 'z2', and 'z3' are in all cases something like signatures, and always bignums. In this case, putting an informative name may be easier:

- 's' --> bn_sig_capsule
- 'z1' --> bn_sig_kfrag1
- 'z2' --> bn_sig_kfrag2
- 'z3' --> bn_sig_challenge_response

What do you think? I'm not very convinced, but since current naming it's a concern for both of you I don't mind changing it.

**Comment by tuxxy** [comment]
I think these are fine. The prefixes add quite a bit of needed context.

**Comment by jMyles** [comment]
@cygnusv: I'm not wowed.

My immediate sense, reading your comment, is that there is a missing metaphor in the PRE ecosystem.

Like HTTP has "reqeust/response", asynchrony has "promise" or "yield" (depending on the control flow), cryptography has "signature" (great metaphor) and "key" (less great metaphor), HTML has "template" (and other metaphors drawn from terminology used with a printing press), and so on: PRE probably needs a coherent metaphor to tell me what these things are and how they intertwine.

**Comment by jMyles** [comment]
Here are some free-form reactions to things that you've said (just words that come to mind from your cues - @KPrasch is good at this game as well, maybe he'll join in):

* bn_sig_challenge_response - affidavit
* bn_sig_capsule - trademark
* bn_sig_kfrag1 - warrant or probate

As for the three ephemeral key points:  Do the `e`, `v`, and `x` have *any* natural coherence at all?  Or are they utterly arbitrary?  If the latter, then I suggest we drop them completely and distinguish them by a denominator that is more obviously arbitrary.

**Comment by cygnusv** [comment]
This is not about metaphors of PRE in general, but about very specific elements of a concrete cryptographic scheme. It's like asking for [RSA](https://en.wikipedia.org/wiki/RSA_(cryptosystem)#Operation) to find colorful names for elements 'e', 'd', 'p', 'q', etc. 

How would one put a name on individual transistors in a CPU? Perhaps a bunch of them, together, could be called an "ALU", or a "register", or whatever, but trying to find meaningful names for individual transistors would be pointless. (sorry for the hyperbole, it's almost 3:00 am here and it's the first example that came up to my mind)

**Comment by jMyles** [comment]
@cygnusv: I don't think I agree about the analogy to CPU registers.

After all, if you are able to attach semantic value like this:
>   's' --> bn_sig_capsule
    'z1' --> bn_sig_kfrag1
    'z2' --> bn_sig_kfrag2
    'z3' --> bn_sig_challenge_response

...then naturally I'm inclined to ask, "what is a challenge response?"  and "what is the `sig` part of these names"?

It's clear to me that at least some of these have cognizable roles which are worth using as names.

**Comment by cygnusv** [comment]
@jMyles yes, the analogy was really bad, I'm afraid :-P (in my defense, it was really late for me!)
My point is that I was using the convention in cryptography and other math-related areas, where variables are named using single characters. In some cases these characters are the first letter of the concept they represent, but in a lot of cases they are just unused letters. This is justified not only because of tradition, but also because of clarity of the mathematical expressions, where variables with more than one letter could be confused with the multiplication of several one-letter variables. 

Having said that I agree that this is not a maths paper, it's code, so it's convenient to improve readability as possible. For this reason I already changed the name of most of the internal variables in the auxiliary classes. However, some of them are still pending, because I still don't know how to name them. For example, a variable that I already named but I'm not very convinced is `point_eph_ni` (previously `x`) in `KFrag`. I have no idea of how to name this, to be honest. I know what it does: it's an ephemeral public key used in a non-interactive Diffie-Hellman key exchange with Bob that allows the transformation of Umbral from interactive re-encryption key generation to non-interactive. But what name should this have? I have no idea. The current name (`point_eph_ni`) reflects both the ephemeral and non-interactive aspects, but I'm not sure if has improved readability (well, at least the `point` part has)

Regarding the `sig` thing, it means that this component is a signature (or part of a signature). Another keyword is `eph` to describe ephemeral public keys.

**Comment by michwill** [comment]
I think, `point_eph_ni` works as soon as you knows the meaning of it (so after you know that it's an ephemeral key to make proxy re-encryption non-interactive, you'll quickly decompress it from the variable name). If it was called `x3` or something meaningless, it'd be a bit harder for the brain to remember the mapping of what it is

**Comment by tuxxy** [comment]
I think I concur with that, as well. If you understand the context of how we're using the ephemeral key to implement non-interactivity, then `point_eph_ni` makes plenty of sense.
