### ISSUE TITLE
Include curve in Capsule serialization

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#81]
Let's include the `curve_nid` in the bytes of a `Capsule` so that `Ursula` can know which curve was used to create it.

**Comment by cygnusv** [comment]
I completely agree. I have to make some changes to Umbral (as discussed in Discord), so let me include this in that PR.

**Comment by jMyles** [comment]
For consistency, does it make sense to also include the `curve_nid` in to/from affine?

**Comment by cygnusv** [comment]
you mean in point serialization?

**Comment by tuxxy** [comment]
Before you guys descend down this path, you have to understand that you're now not trusting the developer as much as you're trusting that serialized bytestring.

Before, you are trusting that the person who implements pyUmbral is using the default curve correctly. OpenSSL can also be trusted, somewhat, to validate this data.

After this, you will be trusting that the person who serializes a Point, BigNum, etc is doing so correctly. OpenSSL is still used to validate it, but you're not really gaining anything other than telling a serializer that this specific curve was used and, imho, misplacing trust into that bytestring instead of the implementation of pyUmbral.

This is a major change, I don't think we should just casually throw it in until we are ready for specific curve agnostic behaviors, which I don't think we are.

**Comment by jMyles** [comment]
I don't see it quite the same way.

Without any curve metadata, there isn't any particular "trust" toward the developer; just an unspoken assumption that Bob and Ursula (or whomever might be sharing the Capsule) are using the same curve.

With curve metadata, we give the recipient *some lens* to decide whether the Capsule is as it purports to be.  Obviously an attacker can make false claims by affixing a curve other than the one actually used to make the Capsule.  But is this any different than the same claim made over whatever other channel is used to achieve this agreement?

If we do provide a canonical method for determining the curve, we needn't immediately concern ourselves with its veracity any more than if we didn't include it.  However, then, when we do add curve-agnostic features, we'll know where to go to add a signature (or whatever verification may be appropriate) to the curve metadata.  This makes sense to me.

Although I'm generally in favor of a YAGNI approach to post-launch features, I'm also given pause by the complications that may arise from having Capsules of multiple valid lengths (given the same curve), which is what will happen if we delay this.

We don't need to move our trust anywhere today.  We're just setting aside a spot to aim trust later, when we come to need it.

**Comment by cygnusv** [comment]
There should exist a way to coordinate Alice, Ursula and Bob to use the same curve for a given `Capsule`. Since this process begins with Alice during encryption, it is reasonable that serialized Capsules include the information of which curve is in use. If not, then Ursula won't have any way of deciding to which curve the compressed points in the Capsule belong.

Having said that, I tend to prefer not having curve agnosticism, but that's a different topic.

**Comment by jMyles** [comment]
@cygnusv: It's true that it's a different topic, but I'm nevertheless interested - what's your one-paragraph reasoning for choosing a single curve (presumably SECP256K1) to the exclusion of all others?  

For my part, I simply don't feel prepared to give such a strong endorsement of the safety of one curve.  I imagined this was the position we wanted the project to take.  As such I wrote this in the docs:

> The matter of which curve to use is the subject of some debate.  If you aren't sure, you might start here:
https://safecurves.cr.yp.to/

> A number of curves are available in the python cryptography library, on which pyumbral depends.
You can find them in cryptography.hazmat.primitives.asymmetric.ec.

> Be careful when choosing a curve - the security of your application depends on it.

> We provide SECP256K1 as a default because it is the basis for a number of crypto-blockchain projects;
we don't otherwise endorse its security.

Do you have a different notion of this?  Do you *want* to otherwise endorse SECP256K1?

**Comment by tuxxy** [comment]
@jMyles That site is pretty useless for us, since it says all the curves we can use are unsafe lol.

The only ones DJB recommends is his curve and some other Edwards/Montogmery curves.

**Comment by jMyles** [comment]
Haha - riiight.  I just grabbed a resource that I knew I had seen around the internets, posted in places I associated with credibility.  But it's completely possible that I picked a lemon.

Is there a similar resource that you prefer?

**Comment by tuxxy** [comment]
DJB's site is really the only one like it.

**Comment by jMyles** [comment]
Is there nobody of credibility picking curves and explaining why?

**Comment by tuxxy** [comment]
DJB did and his group setup guidelines as to what is a "safe curve". His site is the result of that project.

By his standards, secp256k1 is not "safe", nor are any of the NIST curves.
NIST only states that their curves are the ones that should be used for TS/SCI data, but doesn't mention why they should be used.
Other from that, afaik, it's individual researchers, other research groups, and various papers that have been published on the safety of some curves.

There isn't a whole lot of research happening around safe curves in ECC anymore because of everyone's movement and research into Post-Quantum Cryptography and schemes for this.

**Comment by jMyles** [comment]
> Other from that, afaik, it's individual researchers, other research groups, and various papers that have been published on the safety of some curves.

Among these, are there any that speak to you personally?

**Comment by tuxxy** [comment]
For starters:

https://koclab.cs.ucsb.edu/teaching/ecc/project/2015Projects/Bjoernsen.pdf (On secp256k1 security and its applications in Bitcoin)

https://eprint.iacr.org/2013/647.pdf (On high security curves, defines M-511, unsure if even usable for us)

**Comment by tuxxy** [comment]
Also, some further thought, would also appreciate input from @cygnusv on this:

We kind of already specify curve implicitly. We can enforce this by only allowing compressed points in our protocol. This inherently requires a definition of a curve and not in the serialization. DJB points this out on his safecurves site:

>A protocol designer can help protect against this attack by specifying point compression. An implementation that receives a compressed point, such as x and just one bit of y, will naturally detect invalid inputs when it reconstructs the missing coordinate. "

As such, I think adding a byte for this just adds needless serialization complexity. Again, we do not gain _anything_ from adding this in.

**Comment by jMyles** [comment]
I think I need a little boost to fully understand here.

Is your (and DJB's) point simply that decompressing the point from (x, {+|-}) (I hope that notation is OK - I'm sure you understand what I mean) will always give a point {x, y} that's actually on the curve?  I mean, that's obvious, but is it... relevant?  What if the point {x, y} is *actually* a point on the other curve?  It's trivial to find examples of this.

**Comment by jMyles** [comment]
Also (and this is more academic than practical - just for my education): what about the point at infinity?

**Comment by tuxxy** [comment]
Yes, when you decompress the curve, it has to go through the curve equation specific for that curve to find the Y value.

Obviously, when attempting an invalid curve attack, the decompression will catch that because it won't be a valid point on that curve.

For the point at infinity, it won't be a valid key (at least in OpenSSL, IIRC).

For any points that are actually on the curve, this is not an example of an invalid curve attack and has no bad security notions, as far as I'm aware of.

**Comment by jMyles** [comment]
I... see.  I think.  I think I'll benefit from seeing this visually - do you know of a video that shows this on a graph?

So, OK, let's say for the moment that you're right; we've nothing to worry about from invalid curve attacks.  Do we care that somebody might use a curve that is vulnerable to a small subgroup attack?  Won't this at least prevent that?  Or am I off in my thinking there also?

**Comment by jMyles** [comment]
(and, I suppose, also, if somebody is making themselves vulnerable to a small subgroup attack, do we want to just let them be vulnerable?)

**Comment by tuxxy** [comment]
@jMyles secp256k1 is not vulnerable to small subgroup attacks, its `h` value is 1.

As for any videos, I have no idea. You could probably visualize it in Matlab yourself.

**Comment by jMyles** [comment]
@tuxxy: Of course secp256k1 is not vulnerable; that was my point.  If we're supporting other curves, need we concern ourselves with this possibility?

**Comment by tuxxy** [comment]
The only other curves that we could reasonably support (NIST curves, SECG curves, etc) are all twist secure and aren't vulnerable to small subgroup attacks.

**Comment by jMyles** [comment]
:+1: 

As always, your deep knowledge of these topics is very helpful, man.

@cygnusv, where do you reckon this leaves us?

**Comment by tuxxy** [comment]
I'd like to further add that I am not against adding a NID byte _somewhere_, I just don't want it in the point serialization.

I have no problem if this is specified in the policy and can be verified that it's from Alice.

**Comment by cygnusv** [comment]
In my opinion, the summary is:

- Compressed representation is much safer than uncompressed, since one is obliged to check the curve equation, which removes invalid curve attacks
- Dealing with curves with cofactor 1 is much easier than with the rest. Moreover, Umbral was designed for curves of prime order, which implies cofactor is 1.
- We still need a way to know what is the curve to be used in a serialized capsule. If points are represented by 32+1 bytes, how do we know we're using secp256k1 instead of NIST P-256?

**Comment by jMyles** [comment]
Yeah, your Point (heh heh) 3 was where my mind was going.  If you just `gen_rand` a `Point`, there's a fair chance that it will be on both curves.

**Comment by cygnusv** [comment]
Ok, I agree it shouldn't be in the point serialization (I think no one proposed that anyway), but it must be somewhere. The capsule is a potential place, but the policy is fine too, since Alice, Bob and Ursula should all know the policy.

**Comment by tuxxy** [comment]
My thoughts are that when encrypting data with AES in some library, we don't add any metadata that suggests what keysize was used during encryption.

I think this best fits in the Policy data.

**Comment by jMyles** [comment]
I did briefly imagine including it in to/from affine, but yeah I think that `Capsule` (or something even higher level) has always been the pictured place for this metadata.

**Comment by cygnusv** [comment]
Oh, now I see that jmyles talked at some moment about including the curve_nid in to/from_affine. No, including it as part of point serialization would be overkill, and still could be abused. Perhaps the policy is the best place to include it.

**Comment by jMyles** [comment]
I'm going to be making a `PolicyKit` (or something like it) at some point here to reduce the lasagna code (mmm lasagna).  So that seems like the sensible place.

**Comment by jMyles** [comment]
Yeah, thinking about it in to/from_affine was a misfire on my part.

**Comment by KPrasch** [comment]
@jMyles @cygnusv @tuxxy - What's the status with this issue?

**Comment by cygnusv** [comment]
I think this can be closed. Metadata regarding the curve in use for serialized objects (e.g, keys, capsules, etc) should be handled by the application, not pyUmbral.
